setwd("C:/Users/Amit Kulkarni/Documents/R Programming/Capstone Project/10. Taiwan-Customer defaults")
data=read.csv("Taiwan-Customer defaults.csv")
attach(data)

lm1 = lm(default ~ LIMIT_BAL, data = data)
summary(lm1)
lm2 = lm(default ~ SEX, data = data)
summary(lm2)
lm3 = lm(default ~ EDUCATION, data = data)
summary(lm3)
lm4 = lm(default ~ MARRIAGE, data = data)
summary(lm4)
lm5 = lm(default ~ AGE , data = data)
summary(lm5)
lm6 = lm(default ~ Rep0905, data = data)
summary(lm6)
lm7 = lm(default ~ Rep0805, data = data)
summary(lm7)
lm8 = lm(default ~ Rep0705, data = data)
summary(lm8)
lm9 = lm(default ~ Rep0605, data = data)
summary(lm9)
lm10 = lm(default ~ Rep0505, data = data)
summary(lm10)
lm11 = lm(default ~ Rep0405, data = data)
summary(lm11)
lm12 = lm(default ~ Bill0905, data = data)
summary(lm12)
lm13 = lm(default ~ Bill0805, data = data)
summary(lm13)
lm14 = lm(default ~ Bill0705, data = data)
summary(lm14)
lm15 = lm(default ~ Bill0605, data = data)
summary(lm15)
lm16 = lm(default ~ Bill0505, data = data)
summary(lm16)
lm17 = lm(default ~ Bill0405, data = data)
summary(lm17)
lm18 = lm(default ~ PAY_AMT1, data = data)
summary(lm18)
lm = lm(default ~ PAY_AMT1, data = data)
summary(lm)
lm19 = lm(default ~ PAY_AMT1, data = data)
summary(lm19)
lm20 = lm(default ~ PAY_AMT2, data = data)
summary(lm20)
lm21 = lm(default ~ PAY_AMT3, data = data)
summary(lm21)
lm22 = lm(default ~ PAY_AMT4, data = data)
summary(lm22)
lm23 = lm(default ~ PAY_AMT5, data = data)
summary(lm23)
lm24 = lm(default ~ PAY_AMT6, data = data)
summary(lm24)
lm25 = lm(default ~ ., data = data)
summary(lm25)
